### ISSUE TITLE
Govee action not appearing

### ISSUE THREAD

**Issue by dartiss** [evrowe/streamdeck-govee-lighting#1]
I've installed the latest version but, even after restarting it, no Govee action appears in the Stream Deck app.

I tried re-installing it and it stated that it was already installed, so I've ruled that out.

Any idea?

**Comment by evrowe** [comment]
Hi @dartiss—

This plugin is still in development and is not yet ready for use. (The README does state it's in development but doesn't necessarily indicate it is not yet functional). I haven't been working on this much recently but intend to get back to it in the near future; I'd recommend watching or starring the repo so you can keep track of its development and be aware when the initial release is available!

In the meantime, I would recommend installing [BarRaider's API Ninja](https://apps.elgato.com/plugins/com.barraider.apininja) to manually send requests to the Govee API (if you're willing to dig through their API documentation and figure out how to form request bodies to control your lights).

Stay tuned for an official release later this year!
